/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EntriesRouteImport } from './routes/entries'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EntryNewRouteImport } from './routes/entry.new'
import { Route as ComplaintNewRouteImport } from './routes/complaint.new'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSheetRouteImport } from './routes/admin.sheet'
import { Route as AdminGrowthRouteImport } from './routes/admin.growth'
import { Route as AdminEntriesRouteImport } from './routes/admin.entries'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminAnalysisRouteImport } from './routes/admin.analysis'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesRoute = EntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryNewRoute = EntryNewRouteImport.update({
  id: '/entry/new',
  path: '/entry/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintNewRoute = ComplaintNewRouteImport.update({
  id: '/complaint/new',
  path: '/complaint/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSheetRoute = AdminSheetRouteImport.update({
  id: '/admin/sheet',
  path: '/admin/sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGrowthRoute = AdminGrowthRouteImport.update({
  id: '/admin/growth',
  path: '/admin/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntriesRoute = AdminEntriesRouteImport.update({
  id: '/admin/entries',
  path: '/admin/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/admin/complaints',
  path: '/admin/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalysisRoute = AdminAnalysisRouteImport.update({
  id: '/admin/analysis',
  path: '/admin/analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/entries': typeof EntriesRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/sheet': typeof AdminSheetRoute
  '/admin/users': typeof AdminUsersRoute
  '/complaint/new': typeof ComplaintNewRoute
  '/entry/new': typeof EntryNewRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/entries': typeof EntriesRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/sheet': typeof AdminSheetRoute
  '/admin/users': typeof AdminUsersRoute
  '/complaint/new': typeof ComplaintNewRoute
  '/entry/new': typeof EntryNewRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complaints': typeof ComplaintsRoute
  '/entries': typeof EntriesRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/admin/analysis': typeof AdminAnalysisRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/entries': typeof AdminEntriesRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/sheet': typeof AdminSheetRoute
  '/admin/users': typeof AdminUsersRoute
  '/complaint/new': typeof ComplaintNewRoute
  '/entry/new': typeof EntryNewRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complaints'
    | '/entries'
    | '/home'
    | '/profile'
    | '/admin/analysis'
    | '/admin/complaints'
    | '/admin/entries'
    | '/admin/growth'
    | '/admin/sheet'
    | '/admin/users'
    | '/complaint/new'
    | '/entry/new'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complaints'
    | '/entries'
    | '/home'
    | '/profile'
    | '/admin/analysis'
    | '/admin/complaints'
    | '/admin/entries'
    | '/admin/growth'
    | '/admin/sheet'
    | '/admin/users'
    | '/complaint/new'
    | '/entry/new'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/complaints'
    | '/entries'
    | '/home'
    | '/profile'
    | '/admin/analysis'
    | '/admin/complaints'
    | '/admin/entries'
    | '/admin/growth'
    | '/admin/sheet'
    | '/admin/users'
    | '/complaint/new'
    | '/entry/new'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplaintsRoute: typeof ComplaintsRoute
  EntriesRoute: typeof EntriesRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  AdminAnalysisRoute: typeof AdminAnalysisRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminEntriesRoute: typeof AdminEntriesRoute
  AdminGrowthRoute: typeof AdminGrowthRoute
  AdminSheetRoute: typeof AdminSheetRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ComplaintNewRoute: typeof ComplaintNewRoute
  EntryNewRoute: typeof EntryNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries': {
      id: '/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof EntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/new': {
      id: '/entry/new'
      path: '/entry/new'
      fullPath: '/entry/new'
      preLoaderRoute: typeof EntryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint/new': {
      id: '/complaint/new'
      path: '/complaint/new'
      fullPath: '/complaint/new'
      preLoaderRoute: typeof ComplaintNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sheet': {
      id: '/admin/sheet'
      path: '/admin/sheet'
      fullPath: '/admin/sheet'
      preLoaderRoute: typeof AdminSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/growth': {
      id: '/admin/growth'
      path: '/admin/growth'
      fullPath: '/admin/growth'
      preLoaderRoute: typeof AdminGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entries': {
      id: '/admin/entries'
      path: '/admin/entries'
      fullPath: '/admin/entries'
      preLoaderRoute: typeof AdminEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/admin/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analysis': {
      id: '/admin/analysis'
      path: '/admin/analysis'
      fullPath: '/admin/analysis'
      preLoaderRoute: typeof AdminAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplaintsRoute: ComplaintsRoute,
  EntriesRoute: EntriesRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  AdminAnalysisRoute: AdminAnalysisRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminEntriesRoute: AdminEntriesRoute,
  AdminGrowthRoute: AdminGrowthRoute,
  AdminSheetRoute: AdminSheetRoute,
  AdminUsersRoute: AdminUsersRoute,
  ComplaintNewRoute: ComplaintNewRoute,
  EntryNewRoute: EntryNewRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
